events {}

http {
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log warn;

    include /etc/nginx/conf.d/*.conf;

    server {
        listen 80 default_server;
        server_name _;

        location / {
            return 200 "DevOps Sandbox Platform is running\n";
            add_header Content-Type text/plain;
        }
    }
}
